# Generated by Django 6.1 on 2026-08-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
