services:
  web:
    build:
      context: .

    container_name: sam-cu
    restart: unless-stopped

    command: gunicorn hsm.wsgi:application --bind 0.0.0.0:8000 --workers 2

    environment:
      DEBUG: ${DEBUG:-True}

      SECRET_KEY: ${SECRET_KEY:-django-insecure-cg%v6itz2tdc_)3o(se92@r)u_2=b0x9=an%l2t(ce4-(z5bvv}

      # Application is now hosted directly at sam.cu.ac.bd
      BASE_PATH: ${BASE_PATH:-}

      # Django CSRF trusted origin
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-https://sam.cu.ac.bd}

      # PostgreSQL
      POSTGRES_DB: ${POSTGRES_DB:-hallseatmanagment}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_HOST: ${POSTGRES_HOST:-host.docker.internal}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}

    # Optional direct access from host
    # You can remove this if SAM should ONLY be accessible through Traefik.
    # ports:
    #   - "9005:8000"

    volumes:
      - .:/app
      - sam_static:/app/staticfiles
      - sam_media:/app/media

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - proxy

    labels:
      - "traefik.enable=true"

      # =====================================================
      # SAM
      # https://sam.cu.ac.bd
      # =====================================================

      - "traefik.http.routers.sam.rule=Host(`sam.cu.ac.bd`)"
      - "traefik.http.routers.sam.entrypoints=websecure"

      # HTTPS
      - "traefik.http.routers.sam.tls=true"
      - "traefik.http.routers.sam.tls.certresolver=letsencrypt"

      # Django/Gunicorn internal port
      - "traefik.http.services.sam.loadbalancer.server.port=8000"

volumes:
  sam_static:
    name: sam_static
  sam_media:
    name: sam_media

networks:
  proxy:
    external: true