# Generated by Django 6.1 on 2026-08-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('halls', '0002_hall_hall_type_hall_minority_alter_hall_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_halls',
            field=models.ManyToManyField(blank=True, help_text='Halls this user is allowed to manage (used for the hall-wise web UI). Superusers always see every hall.', related_name='managers', to='halls.hall'),
        ),
    ]
