# Generated by Django 6.1 on 2026-08-18 08:08

import django.db.models.deletion
from django.db import migrations, models


def forward_copy_halls_to_single_hall(apps, schema_editor):
    """One user now manages at most one hall: keep the first of their managed halls."""
    User = apps.get_model('accounts', 'User')
    for user in User.objects.exclude(managed_halls=None).iterator():
        hall = user.managed_halls.first()
        if hall is not None:
            user.managed_hall_id = hall.pk
            user.save(update_fields=['managed_hall_id'])


def backward_copy_single_hall_to_m2m(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.exclude(managed_hall=None).iterator():
        user.managed_halls.add(user.managed_hall)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_managed_halls'),
        ('halls', '0002_hall_hall_type_hall_minority_alter_hall_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_hall',
            field=models.ForeignKey(blank=True, help_text='The single hall this user manages (a hall may have many managers). Superusers always see every hall.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='halls.hall'),
        ),
        migrations.RunPython(forward_copy_halls_to_single_hall, backward_copy_single_hall_to_m2m),
        migrations.RemoveField(
            model_name='user',
            name='managed_halls',
        ),
    ]
