from django.core.management.base import BaseCommand
from django.db import transaction

from students.models import Student


STUDENTS = [
    {
        "student_id": '23606010',
        "session": '2022-2023',
        "entity_id": '6060',
        "subject_id": '06061',
        "name_en": 'SADBIN TASLIM',
        "name_bn": 'সাদ বিন তাসলিম',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2004-08-25',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "nid": "20041591624158000",
        "phone": '01847553747',
        "both_address_same": 0,
        "fname_en": 'MD. TASLIM UDDIN',
        "mname_en": 'FARIDA PARVIN',
        "rand_hash": '4865ba390a',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '22903030',
        "session": '2021-2022',
        "entity_id": '9030',
        "subject_id": '09031',
        "name_en": 'N. A. M. MEHEDI HASSAN',
        "name_bn": 'এন.এ.এম. মেহেদী হাসান',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2003-01-01',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": '2865290577',
        "phone": '01786197367',
        "both_address_same": 0,
        "perm_dist": 'Dhaka',
        "fname_en": 'MD. DANESH MIAH',
        "fname_bn": 'প্রফেসর মো. দানেশ মিয়া',
        "fphone": '01320395553',
        "mname_en": 'FARIDA PARVEEN',
        "mname_bn": 'ফরিদা পারভীন',
        "rand_hash": 'af475bf717',
        "student_status": 1,
    },

    {
        "student_id": '19607016',
        "session": '2018-2019',
        "entity_id": '6070',
        "subject_id": '06071',
        "name_en": 'MD. HASAN SAYED RAKIB',
        "name_bn": 'মোঃ হাসান সায়েদ রাকিব',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '1999-08-07',
        "nationality": 'Bangladeshi',
        "phone": '01855744899',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "perm_pcode": '4370',
        "fname_en": 'MD. ABDUS SABUR',
        "fname_bn": 'মোঃ আব্দুস সবুর',
        "fphone": '01819616899',
        "mname_en": 'MOST. AYESHA BEGUM',
        "mname_bn": 'মোছাঃ আয়েশা বেগম',
        "rand_hash": '4aaeabe6ea',
        "student_status": 1,
    },

    {
        "student_id": '24101121',
        "session": '2023-2024',
        "entity_id": '1010',
        "subject_id": '01011',
        "name_en": 'MD. KAWSAR ALI',
        "name_bn": 'মো: কাওছার আলী',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2005-08-01',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": "20051019407025300",
        "phone": '01796607811',
        "both_address_same": 0,
        "perm_dist": 'Bagura',
        "fname_en": 'MD. ABDUR RAJJAK',
        "fname_bn": 'মো: আব্দুর রাজ্জাক',
        "fphone": '01765355640',
        "mname_en": 'MST. KHADIJA BEGUM',
        "mname_bn": 'মোছা:  খাদিজা বেগম',
        "rand_hash": 'b6bca1ea97',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '20202134',
        "session": '2019-2020',
        "entity_id": '2020',
        "subject_id": '02021',
        "name_en": 'TAHMINA KHANUM TUHIN',
        "name_bn": 'তাহমিনা খানম তুহিন',
        "gender": 'FEMALE',
        "dob_ymd": '2000-06-08',
        "nationality": 'Bangladeshi',
        "phone": '01864656591',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "perm_pcode": '4203',
        "fname_en": 'ALI AHEMED',
        "mname_en": 'ANOARA BEGUM',
        "rand_hash": '733533797',
        "student_status": 1,
    },

    {
        "student_id": '19402056',
        "session": '2018-2019',
        "entity_id": '4020',
        "subject_id": '04021',
        "name_en": 'YOUSUF MOHAMMAD ENAN',
        "name_bn": 'ইউসুফ মোহাম্মদ ইনান',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2000-07-16',
        "nationality": 'Bangladeshi',
        "phone": '01838022325',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "perm_pcode": '4386',
        "fname_en": 'ABDUL KADER CHOWDHURL',
        "fname_bn": 'আব্দুল কাদের চৌধুরী',
        "mname_en": 'AYESHA BEGUM',
        "mname_bn": 'আয়েশা বেগম',
        "rand_hash": '32704766a4',
        "student_status": 1,
    },

    {
        "student_id": '23114017',
        "session": '2022-2023',
        "entity_id": '1140',
        "subject_id": '01141',
        "name_en": 'MD. SUJON ALI',
        "name_bn": 'মোঃ সুজন আলী',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2003-03-19',
        "bloodgroup": 'B-',
        "nationality": 'Bangladeshi',
        "nid": '6463413242',
        "phone": '01319457388',
        "both_address_same": 0,
        "fname_en": 'LATE. ASAHFUL',
        "mname_en": 'MST. SARVANU KHATUN',
        "rand_hash": '03d0b0aa8d',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '21113071',
        "session": '2020-2021',
        "entity_id": '1130',
        "subject_id": '01131',
        "name_en": 'MAHIMA MASUD',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2002-10-20',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "phone": '01879709092',
        "both_address_same": 0,
        "perm_addr": 'hulain, Hulain, Patiya, Chittagong',
        "perm_dist": 'Chattogram',
        "fname_en": 'NURUL ABSAR',
        "fname_bn": 'নুরুল আবছার',
        "fphone": '01881689476',
        "mname_en": 'MOTIYA BEGUM',
        "mname_bn": 'কাজী মতিয়া বেগম',
        "rand_hash": '84a5827b4d',
        "student_status": 1,
        "adm_quota": 'General',
    },

    {
        "student_id": '24115008',
        "session": '2023-2024',
        "entity_id": '1150',
        "subject_id": '01151',
        "name_en": 'PRAMANONDO ROY PAPON',
        "name_bn": 'প্রেমানন্দ রায় পাপন',
        "gender": 'MALE',
        "religion": 'HINDUISM',
        "dob_ymd": '2005-12-28',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "nid": '6018981909',
        "phone": '01811151833',
        "both_address_same": 0,
        "perm_dist": 'Rangpur',
        "fname_en": 'MODHUSUDON ROY',
        "fname_bn": 'মধুসুদন রায়',
        "fphone": '01797684930',
        "mname_en": 'PROTIMA RANI',
        "mname_bn": 'প্রতিমা রানী',
        "rand_hash": '4e80eb552c',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '22113004',
        "session": '2021-2022',
        "entity_id": '1130',
        "subject_id": '01131',
        "name_en": 'TASNIM KADER',
        "name_bn": 'তাসনিম কাদের',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2003-01-30',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": '9164681869',
        "phone": '01761614039',
        "both_address_same": 0,
        "perm_dist": 'Chandpur',
        "fname_en": 'ABDUL KADIR',
        "fname_bn": 'আবদুল কাদির',
        "fphone": '01711404421',
        "mname_en": 'LUTHFA AKTER',
        "mname_bn": 'লুৎফা আকতার',
        "rand_hash": 'eb39e39c1e',
        "student_status": 1,
    },

    {
        "student_id": '24406051',
        "session": '2023-2024',
        "entity_id": '4060',
        "subject_id": '04061',
        "name_en": 'JENY AKHTER',
        "name_bn": 'জেনি আকতার',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2003-03-28',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "nid": "20031510447110500",
        "phone": '01883361769',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "fname_en": 'MOHAMMAD YOUSUF',
        "fname_bn": 'মোহাম্মদ ইউসুফ',
        "fphone": '01883361769',
        "mname_en": 'NASIMA AKHTER',
        "mname_bn": 'নাছিমা আকতার',
        "rand_hash": '79c411e0a0',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '21105028',
        "session": '2020-2021',
        "entity_id": '1040',
        "subject_id": '01041',
        "name_en": 'ZARIN NUDAR',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2002-08-01',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "phone": '01608015234',
        "both_address_same": 0,
        "perm_addr": 'Kaliapur,  Laksam,  Cumilla, Sriyang Bazar - 3570, Laksam, Cumilla',
        "perm_dist": 'Cumilla',
        "fname_en": 'PIRZADA MD. SHAFI ULLAH',
        "fname_bn": 'পীরজাদা মোঃ ছফি উল্যাহ',
        "fphone": '01875781643',
        "mname_en": 'JHARNA AKTER',
        "mname_bn": 'ঝর্ণা আক্তার',
        "rand_hash": '729ef61ce4',
        "student_status": 1,
        "adm_quota": 'General',
    },

    {
        "student_id": '20305045',
        "session": '2019-2020',
        "entity_id": '3050',
        "subject_id": '03051',
        "name_en": 'UMME NAHIYAN AHAMED',
        "name_bn": 'উম্মে নাহিয়ান আহমেদ',
        "gender": 'FEMALE',
        "dob_ymd": '2001-05-01',
        "nationality": 'Bangladeshi',
        "phone": '01820627948',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "perm_pcode": '4000',
        "fname_en": 'DILDAR AHAMED',
        "mname_en": 'IRFANA NAHID',
        "rand_hash": 'efc9917a11',
        "student_status": 1,
    },

    {
        "student_id": '22603005',
        "session": '2021-2022',
        "entity_id": '6030',
        "subject_id": '06031',
        "name_en": 'ANIK SARKER',
        "name_bn": 'অনিক সরকার',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2003-12-31',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": "20036118845107400",
        "phone": '01773768254',
        "both_address_same": 0,
        "perm_dist": 'Mymensingh',
        "fname_en": 'MD. MUNTAJ SARKER',
        "fname_bn": 'মো. মুনতাজ সরকার',
        "fphone": '01773768254',
        "rand_hash": '70947aca11',
        "student_status": 1,
    },

    {
        "student_id": '19105036',
        "session": '2018-2019',
        "entity_id": '1040',
        "subject_id": '01041',
        "name_en": 'MD.NAIMUR RAHMAN',
        "name_bn": 'মো: নাঈমুর রহমান',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '1999-11-29',
        "nationality": 'Bangladeshi',
        "phone": '01768371133',
        "both_address_same": 0,
        "perm_dist": 'Jamalpur',
        "perm_pcode": '2000',
        "fname_en": 'MD. ABDUL LATIF',
        "fname_bn": 'আব্দুল লতিফ',
        "fphone": '01622190992',
        "mname_en": 'SHEULI AKTER',
        "mname_bn": 'শিউলি আক্তার',
        "rand_hash": '18f985a1be',
        "student_status": 1,
    },

    {
        "student_id": '21402090',
        "session": '2020-2021',
        "entity_id": '4020',
        "subject_id": '04021',
        "name_en": 'TAHASIN TABASSUM AKTER',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2001-12-12',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "phone": '01586354561',
        "both_address_same": 0,
        "perm_addr": 'North Jashpur, North Jashpur, Chhagalnaiya, Feni',
        "perm_dist": 'Feni',
        "fname_en": 'MOAZZAM HOSSAIN PATUARY',
        "fname_bn": 'মোয়াজ্জম হোসেন পাটোয়ারী',
        "fphone": '01819725273',
        "mname_en": 'NILUFA AKTER',
        "mname_bn": 'নিলুফা আক্তার',
        "rand_hash": 'a334eda5f9',
        "student_status": 1,
        "adm_quota": 'General',
    },

    {
        "student_id": '21114030',
        "session": '2020-2021',
        "entity_id": '1140',
        "subject_id": '01141',
        "name_en": 'RASEL AKTER',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2002-04-01',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "phone": '01773061669',
        "both_address_same": 0,
        "perm_addr": 'Chalkpranpur, Kharitala, Kaligonj, Satkhira',
        "perm_dist": 'Satkhira',
        "fname_en": 'GOLAM RABBANI',
        "fname_bn": 'গোলাম রব্বানী',
        "fphone": '01739006111',
        "mname_en": 'RAZIA KHATUN',
        "mname_bn": 'রাজিয়া খাতুন',
        "rand_hash": '838b1a985c',
        "student_status": 1,
        "adm_quota": 'General',
    },

    {
        "student_id": '2501081056',
        "session": '2024-2025',
        "entity_id": '01080',
        "subject_id": '01081',
        "name_en": 'SAGAR CHAKMA',
        "gender": 'MALE',
        "religion": 'BUDDHISM',
        "dob_ymd": '2005-01-13',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "phone": '01613267084',
        "both_address_same": 0,
        "fname_en": 'SHANTI LAL CHAKMA',
        "fphone": '01575410668',
        "mname_en": 'KALO CHAKMA',
        "mphone": '01575410668',
        "rand_hash": 'cb2ff1577f',
        "hall_code": 'HALATS',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '19106018',
        "session": '2018-2019',
        "entity_id": '1060',
        "subject_id": '01061',
        "name_en": 'ANTARA BARUA',
        "name_bn": 'অন্তরা বড়ুয়া',
        "gender": 'FEMALE',
        "religion": 'BUDDHISM',
        "dob_ymd": '1999-09-21',
        "nationality": 'Bangladeshi',
        "phone": '01913030661',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "perm_pcode": '4346',
        "fname_en": 'AMALENDU BIKASH BARUA',
        "fname_bn": 'অমলেন্দু বিকাশ বড়ুয়া',
        "fphone": '01913030661',
        "mname_en": 'KHUKU BARUA',
        "mname_bn": 'খুকু বড়ুয়া',
        "rand_hash": '7a12693e31',
        "student_status": 1,
    },

    {
        "student_id": '22405030',
        "session": '2021-2022',
        "entity_id": '4050',
        "subject_id": '04051',
        "name_en": 'MD. RAKIB BIN KASHEM',
        "name_bn": 'মো: রাকিব বিন  কাশেম',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2002-09-14',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": '2415551742',
        "phone": '01885396821',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "fname_en": 'ABUL KASHEM CHOWDHURY',
        "fname_bn": 'আবুল কাশেম চৌধুরী',
        "fphone": '01885396821',
        "mname_en": 'FATEMA BEGUM',
        "mname_bn": 'ফাতেমা বেগম',
        "rand_hash": '2ca8a0144f',
        "student_status": 1,
    },

    {
        "student_id": '19407058',
        "session": '2018-2019',
        "entity_id": '4070',
        "subject_id": '04071',
        "name_en": 'GIAS UDDIN RIADH',
        "name_bn": 'গিয়াস উদ্দিন রিয়াদ',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '1999-08-27',
        "nationality": 'Bangladeshi',
        "both_address_same": 0,
        "perm_dist": 'Feni',
        "fname_en": 'JALAL AHMED',
        "fname_bn": 'জালাল আহম্মদ',
        "mname_en": 'JOHURA  BEGUM',
        "mname_bn": 'জোহুরা বেগম',
        "rand_hash": 'd657ae1587',
        "student_status": 1,
    },

    {
        "student_id": '23202126',
        "session": '2022-2023',
        "entity_id": '2020',
        "subject_id": '02021',
        "name_en": 'MD. RASHEDUL ISLAM',
        "name_bn": 'মো:রাশেদুল ইসলাম',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2003-12-25',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "nid": "20035013988103000",
        "phone": '01322611648',
        "both_address_same": 0,
        "fname_en": 'MD. ABDUL GAFUR MALITHA',
        "mname_en": 'MST. AMBIA KHATUN',
        "rand_hash": '32ab24a1ee',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '19605039',
        "session": '2018-2019',
        "entity_id": '6050',
        "subject_id": '06051',
        "name_en": 'SABRINA MOMTAJ SAIMA',
        "name_bn": 'সাবরিনা মমতাজ সায়মা',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2000-05-05',
        "nationality": 'Bangladeshi',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "perm_pcode": '4202',
        "fname_en": 'M. A. MALEK BHUIYAN',
        "fname_bn": 'এম এ মালেক ভূঞা',
        "fphone": '01819360653',
        "mname_en": 'MOMTAJ BEGUM',
        "mname_bn": 'মমতাজ বেগম',
        "rand_hash": 'bd2956c105',
        "student_status": 1,
    },

    {
        "student_id": '2601101082',
        "session": '2025-2026',
        "entity_id": '01100',
        "subject_id": '01101',
        "name_en": 'MD. ABDUL MOJID',
        "name_bn": 'মোঃ আব্দুল মজিদ',
        "gender": 'MALE',
        "religion": 'Islam',
        "dob": '22/02/2006',
        "dob_ymd": '2006-02-22',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": '7822699281',
        "phone": '01622644422',
        "both_address_same": 1,
        "perm_addr": 'Abdul Mannaner Notun Bari, Shebandi, Barma, East Joara, Chattogram',
        "perm_dist": 'Chattogram',
        "perm_pcode": '4383',
        "pres_addr": 'Abdul Mannaner Notun Bari, Shebandi, Barma, East Joara, Chattogram',
        "pres_dist": 'Chattogram',
        "pres_pcode": '4383',
        "fname_en": 'MD. ABDUL MANNAN',
        "fname_bn": 'মোঃ আব্দুল মন্নান',
        "fnid": '4215360119',
        "foccupation": 'Deceased',
        "fphone": '01873145495',
        "mname_en": 'DILU ARA BEGUM',
        "mname_bn": 'দিলু আরা বেগম',
        "mnid": '1511828494426',
        "mphone": '01775814731',
        "rand_hash": 'ff78618e0d',
        "hall_code": 'HALSUH',
        "student_status": 1,
        "adm_unit": 'B2',
        "adm_quota": 'GENERAL',
        "adm_roll": '401804',
        "hsc_group": 'hum',
        "adm_merit": '27',
        "user_id": 89819,
        "username": 'mad25148614',
    },

    {
        "student_id": '21202111',
        "session": '2020-2021',
        "entity_id": '2020',
        "subject_id": '02021',
        "name_en": 'MD. RIAD HASAN ZION',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2002-12-14',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "phone": '01729831804',
        "both_address_same": 0,
        "perm_addr": 'খুলিয়াতারী, রাজারহাট, রাজারহাট, Kurigram',
        "perm_dist": 'Kurigram',
        "fname_en": 'MD. ABDUL MANNAN',
        "fname_bn": 'মোঃ আব্দুল মান্নান',
        "fphone": '01751086831',
        "mname_en": 'MOST. SALEHA BEGUM',
        "mname_bn": 'মোছাঃ সালেহা বেগম',
        "rand_hash": '9cebbd8dbf',
        "student_status": 1,
        "adm_quota": 'Quota',
    },

    {
        "student_id": '23602063',
        "session": '2022-2023',
        "entity_id": '6020',
        "subject_id": '06021',
        "name_en": 'MEHE JABIN MAISHA',
        "name_bn": 'মেহেজাবিন মায়িশা',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2004-03-30',
        "bloodgroup": 'AB+',
        "nationality": 'Bangladeshi',
        "phone": '01752583094',
        "both_address_same": 0,
        "perm_dist": 'Gaibandha',
        "fname_en": 'MD. MIZANUR RAHMAN',
        "fname_bn": 'মো: মিজানুর রহমান',
        "fphone": '01752583094',
        "mname_en": 'MST. ISRAT JAHAN',
        "mname_bn": 'মোছা: ইসরাত জাহান',
        "rand_hash": '6f71139855',
        "student_status": 1,
        "adm_quota": 'FFQ1',
    },

    {
        "student_id": '24117028',
        "session": '2023-2024',
        "entity_id": '1170',
        "subject_id": '01171',
        "name_en": 'AYESA JAMAN TAMANNA',
        "name_bn": 'আয়েশা জামান তামান্না',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2005-01-07',
        "bloodgroup": 'AB+',
        "nationality": 'Bangladeshi',
        "nid": "20057316494015200",
        "phone": '01984167507',
        "both_address_same": 0,
        "perm_dist": 'Nilphamari',
        "fname_en": 'MD.AMIRUZZAMAN',
        "fname_bn": 'মোঃ আমিরুজ্জামান',
        "fphone": '01920046464',
        "mname_en": 'SELINA JAMAN',
        "mname_bn": 'সেলিনা জামান',
        "rand_hash": '0406ca6f38',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '21404065',
        "session": '2020-2021',
        "entity_id": '4040',
        "subject_id": '04041',
        "name_en": 'REDOUN  ISLAM ROKY',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2002-11-20',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "phone": '01789408477',
        "both_address_same": 0,
        "perm_addr": 'west dhemsha Satkania  Chattogram, Satkania, Satkania, Chittagong',
        "perm_dist": 'Chattogram',
        "fname_en": 'MOHAMMAD IBRAHIM',
        "fname_bn": 'মোহাম্মদ  ইব্রাহিম',
        "fphone": '01789408477',
        "mname_en": 'NURJAHAN BEGUM',
        "mname_bn": 'নুরজাহান বেগম',
        "rand_hash": '73f5a6871a',
        "student_status": 1,
        "adm_quota": 'General',
    },

    {
        "student_id": '20304032',
        "session": '2019-2020',
        "entity_id": '3040',
        "subject_id": '03041',
        "name_en": 'PRIYA BISWAS',
        "name_bn": 'প্রিয়া বিশ্বাস',
        "gender": 'FEMALE',
        "dob_ymd": '2000-10-27',
        "nationality": 'Bangladeshi',
        "phone": '01866603447',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "perm_pcode": '4000',
        "fname_en": 'TAPON BISWAS',
        "mname_en": 'KABITA BISWAS',
        "rand_hash": '284e7d7d3d',
        "student_status": 1,
    },

    {
        "student_id": '24602080',
        "session": '2023-2024',
        "entity_id": '6020',
        "subject_id": '06021',
        "name_en": 'SUMAIYA AFRIN TISMA',
        "name_bn": 'সুমাইয়া আফরিন তিসমা',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2004-11-20',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": '3324505100',
        "phone": '01811591042',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "fname_en": 'MD. SOLIMAN',
        "fname_bn": 'মোঃ সোলায়মান',
        "fphone": '01710936937',
        "mname_en": 'SHAMIMA AKTHER',
        "mname_bn": 'শামিমা আকতার',
        "rand_hash": '183451641f',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '20104120',
        "session": '2019-2020',
        "entity_id": '1050',
        "subject_id": '01051',
        "name_en": 'MD. ABU HANIF MIAH',
        "name_bn": 'মোঃ আবু হানিফ মিয়া',
        "gender": 'MALE',
        "dob_ymd": '2001-07-14',
        "nationality": 'Bangladeshi',
        "phone": '01765834548',
        "both_address_same": 0,
        "perm_dist": 'Tangail',
        "perm_pcode": '1936',
        "fname_en": 'MD. SONA MIAH',
        "mname_en": 'FULMALA BEGUM',
        "rand_hash": '1d75664fbf',
        "student_status": 1,
    },

    {
        "student_id": '21607027',
        "session": '2020-2021',
        "entity_id": '6070',
        "subject_id": '06071',
        "name_en": 'MOHAMMAD FUWAD HASAN',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2001-01-14',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "phone": '01834080487',
        "both_address_same": 0,
        "perm_addr": 'Vill- Mogdhara, Uttar Mogdhara, Sandwip, Chittagong',
        "perm_dist": 'Chattogram',
        "fname_en": 'ABDUR RAHIM',
        "fname_bn": 'আব্দুর রহিম',
        "mname_en": 'ZARINA BEGUM',
        "mname_bn": 'জরিনা বেগম',
        "rand_hash": '2df669764d',
        "student_status": 1,
        "adm_quota": 'General',
    },

    {
        "student_id": '23112020',
        "session": '2022-2023',
        "entity_id": '1120',
        "subject_id": '01121',
        "name_en": 'MD. RAYHAN ALI',
        "name_bn": 'মো: রায়হান আলী',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2004-12-21',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "nid": '8274384273',
        "phone": '01948487062',
        "both_address_same": 0,
        "fname_en": 'MD. AMINUR RAHMAN',
        "mname_en": 'MST. RABEYA BEGUM',
        "rand_hash": '7689c74050',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '22303012',
        "session": '2021-2022',
        "entity_id": '3030',
        "subject_id": '03031',
        "name_en": 'MIR TURSHA ISLAM MIM',
        "name_bn": 'মীর তুরসা ইসলাম মীম',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2002-06-12',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "nid": '6014417445',
        "phone": '01891651122',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "fname_en": 'MIR MD. SHAMIMUL ISLAM',
        "fname_bn": 'মীর মোঃ শামীমুল ইসলাম',
        "fphone": '01817258259',
        "mname_en": 'NASRIN AKHTER RANU',
        "mname_bn": 'নাসরীন আকতার',
        "rand_hash": '1b054c87de',
        "student_status": 1,
    },

    {
        "student_id": '22302115',
        "session": '2021-2022',
        "entity_id": '3020',
        "subject_id": '03021',
        "name_en": 'JOY CHAKMA',
        "name_bn": 'জয় চাকমা',
        "gender": 'MALE',
        "religion": 'BUDDHISM',
        "dob_ymd": '2004-02-25',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": "20048428703054800",
        "phone": '01869041706',
        "both_address_same": 0,
        "perm_dist": 'Rangamati',
        "fname_en": 'SUGATA PRIYA CHAKMA',
        "fname_bn": 'সুগত প্রিয় চাকমা',
        "fphone": '01869041706',
        "mname_en": 'SABIKA CHAKMA',
        "mname_bn": 'সেবিকা চাকমা',
        "rand_hash": '39c23b8b1c',
        "student_status": 1,
    },

    {
        "student_id": '23407058',
        "session": '2022-2023',
        "entity_id": '4070',
        "subject_id": '04071',
        "name_en": 'MASHNOON TAHHIA',
        "name_bn": 'মাশনুন তাহ্হিয়া',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2003-10-05',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": '3318693334',
        "phone": '01608225509',
        "both_address_same": 0,
        "fname_en": 'MD. MOZAFFER HOSSAIN',
        "mname_en": 'PARVIN AKHTER',
        "rand_hash": '78e78a0013',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '24201030',
        "session": '2023-2024',
        "entity_id": '2010',
        "subject_id": '02011',
        "name_en": 'RUBAIYA BINTE RAKATULLAH',
        "name_bn": 'রুবাইয়া বিনতে রাকাতুল্লাহ্',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2005-12-20',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "nid": "20047610531012600",
        "phone": '01719061541',
        "both_address_same": 0,
        "perm_dist": 'Pabna',
        "fname_en": 'MD. RAKATULLAH',
        "fname_bn": 'মোঃ রাকাতুল্লাহ্',
        "fphone": '01718908472',
        "mname_en": 'MST. SHAJEDA KHATUN',
        "mname_bn": 'মোছাঃ সাজেদা খাতুন',
        "rand_hash": '8495b9915d',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '24404148',
        "session": '2023-2024',
        "entity_id": '4040',
        "subject_id": '04041',
        "name_en": 'RITU SARKER',
        "name_bn": 'রীতু সরকার',
        "gender": 'MALE',
        "religion": 'HINDUISM',
        "dob_ymd": '2005-08-31',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": "20055418066001200",
        "phone": '01873428125',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "fname_en": 'DHIREN CHANDRA SARKER',
        "fname_bn": 'ধীরেন চন্দ্র সরকার',
        "fphone": '01745891171',
        "mname_en": 'KALPANA SARKER',
        "mname_bn": 'কল্পনা সরকার',
        "rand_hash": 'c9295409b2',
        "student_status": 1,
        "adm_quota": 'FFQ1',
    },

    {
        "student_id": '19202138',
        "session": '2018-2019',
        "entity_id": '2020',
        "subject_id": '02021',
        "name_en": 'ROBIUL AOWAL',
        "name_bn": 'রবিউল আওয়াল',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '1999-08-23',
        "nationality": 'Bangladeshi',
        "phone": '01789359772',
        "both_address_same": 0,
        "perm_dist": 'Panchagarh',
        "perm_pcode": '5000',
        "fname_en": 'LUTFAR RAHMAN',
        "fname_bn": 'লু্ৎফর রহমান',
        "fphone": '01767511343',
        "mname_en": 'RAHIMA KHATUN',
        "mname_bn": 'রহিমা খাতুন',
        "rand_hash": 'd1aab216e7',
        "student_status": 1,
    },

    {
        "student_id": '2606041031',
        "session": '2025-2026',
        "entity_id": '06040',
        "subject_id": '06041',
        "name_en": 'EYAFIZ AMIN SUNAM',
        "name_bn": 'ইয়াফিজ আমিন সুনাম',
        "gender": 'MALE',
        "religion": 'Islam',
        "dob": '22/03/2006',
        "dob_ymd": '2006-03-22',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": '20061591639144942',
        "phone": '01308785457',
        "both_address_same": 0,
        "perm_addr": 'Aminul Haque Sukanirs New House, South Halishahar, Sailors Colony, Ward No 39, Chitt, Chittagong Sadar, Chattogram',
        "perm_dist": 'Chattogram',
        "perm_pcode": '4218',
        "pres_addr": '14 No Airport Colony Road, Patenga, Chattogram, Ward No 41, Chittagong, Chittagong Sadar, Chattogram',
        "pres_dist": 'Chattogram',
        "pres_pcode": '4205',
        "fname_en": 'MD ALI AZAM',
        "fname_bn": 'মোঃ আলী আজম',
        "fnid": '3253678365',
        "foccupation": 'Business',
        "fphone": '01308785457',
        "mname_en": 'KANIZ FATHIMA',
        "mname_bn": 'কানিজ ফাতিমা',
        "mnid": '8203704807',
        "mphone": '01634392223',
        "rand_hash": '9cdfbab415',
        "hall_code": 'HALRAB',
        "student_status": 1,
        "adm_unit": 'A',
        "adm_quota": 'GENERAL',
        "adm_roll": '117936',
        "hsc_group": 'sci',
        "adm_merit": '594',
        "user_id": 81114,
        "username": 'chi25103508',
    },

    {
        "student_id": '2601011058',
        "session": '2025-2026',
        "entity_id": '01010',
        "subject_id": '01011',
        "name_en": 'NOWRIN ALAM TANHA',
        "name_bn": 'নওরিন আলম তানহা',
        "gender": 'FEMALE',
        "religion": 'Islam',
        "dob": '21/12/2007',
        "dob_ymd": '2007-12-21',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": '20071517463124365',
        "phone": '01821189004',
        "both_address_same": 1,
        "perm_addr": 'Anowar Sow Bari, Raozan, Chattogram, 13, Guzra, Rouzan, Chattogram',
        "perm_dist": 'Chattogram',
        "perm_pcode": '4346',
        "pres_addr": 'Anowar Sowdagor Bari,Raozan,Chattogram, 13, Guzra, Rouzan, Chattogram',
        "pres_dist": 'Chattogram',
        "pres_pcode": '4346',
        "fname_en": 'MOHAMMAD DIDARUL ALAM',
        "fname_bn": 'মোঃ দিদারুল আলম',
        "fnid": '1517463714246',
        "foccupation": 'Business',
        "fphone": '01819809026',
        "mname_en": 'RAHANA PARVIN',
        "mname_bn": 'রেহেনা পারভীন',
        "mnid": '19781517463714247',
        "mphone": '01852403752',
        "rand_hash": '4356f30eac',
        "hall_code": 'HALSNR',
        "student_status": 1,
        "adm_unit": 'B',
        "adm_quota": 'GENERAL',
        "adm_roll": '205211',
        "hsc_group": 'hum',
        "adm_merit": '175',
        "user_id": 90416,
        "username": 'chi25300324',
    },

    {
        "student_id": '22204069',
        "session": '2021-2022',
        "entity_id": '2040',
        "subject_id": '02041',
        "name_en": 'NUSRAT YOUNUS ESHA',
        "name_bn": 'নুসরাত ইউনুছ ইশা',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2004-01-24',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": "20041591627122500",
        "phone": '01772956904',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "fname_en": 'MD. YOUNUS',
        "fname_bn": 'মোঃ ইউনুছ',
        "fphone": '01772956904',
        "mname_en": 'YESMIN AKTER',
        "mname_bn": 'ইয়াছমিন আক্তার',
        "rand_hash": '9a674722b6',
        "student_status": 1,
    },

    {
        "student_id": '20304077',
        "session": '2019-2020',
        "entity_id": '3040',
        "subject_id": '03041',
        "name_en": 'MD. NAHIAN CHOWDHURY',
        "name_bn": 'মোঃ নাহিয়ান চৌধুরী',
        "gender": 'MALE',
        "dob_ymd": '2001-02-19',
        "nationality": 'Bangladeshi',
        "phone": '01823468058',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "perm_pcode": '4330',
        "fname_en": 'MD. SHAHJAHAN CHOWDHURY',
        "mname_en": 'MOSAMMAT JAHEDA BEGUM',
        "rand_hash": '30369025db',
        "student_status": 1,
    },

    {
        "student_id": '2504011012',
        "session": '2024-2025',
        "entity_id": '04010',
        "subject_id": '04011',
        "name_en": 'MOSSAMAT MIFTAHUL JANNAT NAYON',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2005-12-12',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "phone": '01865801851',
        "both_address_same": 0,
        "fname_en": 'MD. ISMAIL',
        "fphone": '01814051246',
        "mname_en": 'MOSSAMAT KAMRU NAHAR BEGUM',
        "mphone": '01814051246',
        "rand_hash": '6d62f0d098',
        "hall_code": 'HALKHZ',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '21302024',
        "session": '2020-2021',
        "entity_id": '3020',
        "subject_id": '03021',
        "name_en": 'NYMA SIDDIQA',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2002-05-25',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "phone": '01834190836',
        "both_address_same": 0,
        "perm_addr": 'Phatali,  P.M Khali , Cox, s Bazar, Kharuliyaa, Sadar, Coxs_Bazar',
        "perm_dist": "Cox's Bazar",
        "fname_en": 'NURUZZAMAN',
        "fname_bn": 'নুরুজ্জামান',
        "fphone": '01753844994',
        "mname_en": 'MONU ARA BEGUM',
        "mname_bn": 'মনোয়ারা বেগম',
        "rand_hash": 'f731296243',
        "student_status": 1,
        "adm_quota": 'General',
    },

    {
        "student_id": '22108046',
        "session": '2021-2022',
        "entity_id": '1080',
        "subject_id": '01081',
        "name_en": 'TISHA BARUA',
        "name_bn": 'তিশা বড়ুয়া',
        "gender": 'FEMALE',
        "religion": 'BUDDHISM',
        "dob_ymd": '2003-12-02',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": '6460334516',
        "phone": '01616862234',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "fname_en": 'ASHIM BARUA',
        "fname_bn": 'অসীম বড়ুয়া',
        "fphone": '01616862234',
        "mname_en": 'SHILPI BARUA',
        "mname_bn": 'শিল্পী বড়ুয়া',
        "rand_hash": '92ddc2d670',
        "student_status": 1,
    },

    {
        "student_id": '22405099',
        "session": '2021-2022',
        "entity_id": '4050',
        "subject_id": '04051',
        "name_en": 'JUBAIRIA MEHERIN',
        "name_bn": 'জুবাইরিয়া মেহেরীন',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2003-02-02',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": "20033325505129100",
        "phone": '01838467116',
        "both_address_same": 0,
        "perm_dist": 'Gazipur',
        "fname_en": 'MD. ZAKIRUL ISLAM',
        "fname_bn": 'মোঃ জাকিরুল ইসলাম আকন্দ',
        "fphone": '01711192156',
        "mname_en": 'MAHBUBA AKAND',
        "mname_bn": 'মিসেস মাহবুবা আকন্দ',
        "rand_hash": 'e10abcab6e',
        "student_status": 1,
    },

    {
        "student_id": '2503041072',
        "session": '2024-2025',
        "entity_id": '03040',
        "subject_id": '03041',
        "name_en": 'TASIN CHOWDHURY',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2006-11-08',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "phone": '01758990159',
        "both_address_same": 0,
        "fname_en": 'TAREK SIRAJ CHOWDHURY',
        "fphone": '01819338258',
        "mname_en": 'RAZINA AKTER',
        "mphone": '01979338258',
        "rand_hash": '0e137783f3',
        "hall_code": 'HALSJL',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '2603061044',
        "session": '2025-2026',
        "entity_id": '03060',
        "subject_id": '03061',
        "name_en": 'MOHAMMED HASAN RUHI',
        "name_bn": 'মোহাম্মদ হাছান রুহি',
        "gender": 'MALE',
        "religion": 'Islam',
        "dob": '16/06/2006',
        "dob_ymd": '2006-06-16',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": '4224878985',
        "phone": '01328357997',
        "both_address_same": 1,
        "perm_addr": 'Haji Saheb Mia Bari, Pran Hori Das Road, Middle Soraipara, Pahartali, Chittagong, Ward No-12, Pahartoli, Chittagong Sadar, Chattogram',
        "perm_dist": 'Chattogram',
        "perm_pcode": '4202',
        "pres_addr": 'Haji Saheb Mia Bari, Pran Hori Das Road, Middle Soraipara, Pahartali, Chittagong, Ward No-12, Pahartoli, Chittagong Sadar, Chattogram',
        "pres_dist": 'Chattogram',
        "pres_pcode": '4202',
        "fname_en": 'MOHAMMED JAHUR ALAM',
        "fname_bn": 'মোহাম্মদ জহুর আলম',
        "fnid": '3279153575',
        "foccupation": 'Servicemen',
        "fphone": '01832804241',
        "mname_en": 'RABEYA BEGUM',
        "mname_bn": 'রাবেয়া বেগম',
        "mnid": '1929220638',
        "mphone": '01330682468',
        "rand_hash": '88e6274702',
        "hall_code": 'HALSJL',
        "student_status": 1,
        "adm_unit": 'C',
        "adm_quota": 'GENERAL',
        "adm_roll": '508474',
        "hsc_group": 'bus',
        "adm_merit": '396',
        "user_id": 85766,
        "username": 'chi24525849',
    },

    {
        "student_id": '20114047',
        "session": '2019-2020',
        "entity_id": '1140',
        "subject_id": '01141',
        "name_en": 'YEASMIN AKTHER BEAUTY',
        "name_bn": 'ইয়াসমিন আক্তার বিউটি',
        "gender": 'FEMALE',
        "dob_ymd": '2001-08-10',
        "nationality": 'Bangladeshi',
        "phone": '01881494846',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "perm_pcode": '4212',
        "fname_en": 'KHORSHEDUL ALAM',
        "mname_en": 'KHORSHEDA BEGUM',
        "rand_hash": '3f5bba8096',
        "student_status": 1,
    },

    {
        "student_id": '19204117',
        "session": '2018-2019',
        "entity_id": '2040',
        "subject_id": '02041',
        "name_en": 'ABU RAYHAN',
        "name_bn": 'আবু রায়হান ',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2000-01-15',
        "nationality": 'Bangladeshi',
        "phone": '01815617944',
        "both_address_same": 0,
        "perm_dist": 'Mymensingh',
        "perm_pcode": '2210',
        "fname_en": 'ABDUS SALAM',
        "fname_bn": 'আব্দুস সালাম ',
        "mname_en": 'RAHELA BEGUM',
        "mname_bn": 'রাহেলা বেগম ',
        "rand_hash": '23fe4842aa',
        "student_status": 1,
    },

    {
        "student_id": '20501105',
        "session": '2019-2020',
        "entity_id": '5010',
        "subject_id": '05011',
        "name_en": 'CHAITI MANDAL',
        "name_bn": 'চৈতী মণ্ডল',
        "gender": 'FEMALE',
        "dob_ymd": '2001-09-21',
        "nationality": 'Bangladeshi',
        "phone": '01738685949',
        "both_address_same": 0,
        "perm_dist": 'Dhaka',
        "perm_pcode": '1320',
        "fname_en": 'NANI GOPAL MANDAL',
        "mname_en": 'PROMILA MANDAL',
        "rand_hash": '7fa40d2827',
        "student_status": 1,
    },

    {
        "student_id": '19901003',
        "session": '2018-2019',
        "entity_id": '9010',
        "subject_id": '09011',
        "name_en": 'AISHARJA BARUA CHOWDHURY',
        "name_bn": 'ঐশ্বর্য বড়ুয়া চৌধুরী ',
        "gender": 'FEMALE',
        "religion": 'BUDDHISM',
        "dob_ymd": '1999-03-15',
        "nationality": 'Bangladeshi',
        "phone": '01812895402',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "perm_pcode": '4370',
        "fname_en": 'DIBAKAR CHOWDHURY',
        "fname_bn": 'দিবাকর চৌধুরী ',
        "fphone": '01858391205',
        "mname_en": 'KSHAMA CHOWDHURY',
        "mname_bn": 'ক্ষেমা চৌধুরী ',
        "rand_hash": '842099d18c',
        "student_status": 1,
    },

    {
        "student_id": '24115038',
        "session": '2023-2024',
        "entity_id": '1150',
        "subject_id": '01151',
        "name_en": 'NILOY SARKAR',
        "name_bn": 'নিলয় সরকার',
        "gender": 'MALE',
        "religion": 'HINDUISM',
        "dob_ymd": '2004-08-12',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": '9587266397',
        "phone": '01757805360',
        "both_address_same": 0,
        "perm_dist": 'Gaibandha',
        "fname_en": 'ASIM SARKAR',
        "fname_bn": 'অসীম সরকার',
        "fphone": '01742491933',
        "mname_en": 'CHAMELI RANI SARKAR',
        "mname_bn": 'চামেলী রাণী সরকার',
        "rand_hash": 'faba32fb0c',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '2501071065',
        "session": '2024-2025',
        "entity_id": '01070',
        "subject_id": '01071',
        "name_en": 'ABDUL HALIM',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2005-04-23',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "phone": '01576762526',
        "both_address_same": 0,
        "fname_en": 'ABDUL AMIN',
        "fphone": '01857913554',
        "mname_en": 'AYESHA KHATUN',
        "mphone": '01889517143',
        "rand_hash": 'b256b4689b',
        "hall_code": 'HALFRD',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '20404053',
        "session": '2019-2020',
        "entity_id": '4040',
        "subject_id": '04041',
        "name_en": 'MD ASHIKUR RAHMAN',
        "name_bn": 'মোঃ আশিকুর রহমান',
        "gender": 'MALE',
        "dob_ymd": '2001-08-10',
        "nationality": 'Bangladeshi',
        "phone": '01783791726',
        "both_address_same": 0,
        "perm_dist": 'Jessore',
        "perm_pcode": '7410',
        "fname_en": 'MD ANISUR RAHMAN',
        "mname_en": 'LUCKY BEGUM',
        "rand_hash": 'cedf6f1b98',
        "student_status": 1,
    },

    {
        "student_id": '19403188',
        "session": '2018-2019',
        "entity_id": '4030',
        "subject_id": '04031',
        "name_en": 'TAHIRA IBNAT TARIN',
        "name_bn": 'তাহিরা ইবনাত তারিন',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2000-12-20',
        "nationality": 'Bangladeshi',
        "phone": '01960203151',
        "both_address_same": 0,
        "perm_dist": 'Cumilla',
        "perm_pcode": '3530',
        "fname_en": 'MD. MOSTOFA KAMAL  SARKER',
        "fname_bn": 'মোঃ মোস্তফা কামাল সরকার',
        "fphone": '01717587474',
        "mname_en": 'SALEHA LOVELY',
        "mname_bn": 'ছালেহা লাভলী',
        "rand_hash": '37ca653ba8',
        "student_status": 1,
    },

    {
        "student_id": '20103093',
        "session": '2019-2020',
        "entity_id": '1030',
        "subject_id": '01031',
        "name_en": 'MD. SHAMIUL ISLAM',
        "name_bn": 'মো: সামিউল ইসলাম',
        "gender": 'MALE',
        "dob_ymd": '2000-06-17',
        "nationality": 'Bangladeshi',
        "phone": '01799884731',
        "both_address_same": 0,
        "perm_dist": 'Dinajpur',
        "perm_pcode": '5266',
        "fname_en": 'MD. NAZRUL ISLAM',
        "mname_en": 'MST. MARINA BEGUM',
        "rand_hash": '3e8a434ef0',
        "student_status": 1,
    },

    {
        "student_id": '2503021053',
        "session": '2024-2025',
        "entity_id": '03020',
        "subject_id": '03021',
        "name_en": 'IRFAN',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2006-06-15',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "phone": '01319043340',
        "both_address_same": 0,
        "fname_en": 'ABUL KASHEM',
        "fphone": '01617793190',
        "mname_en": 'SHAMIM AKTER HASHEMI RINA',
        "mphone": '01882838033',
        "rand_hash": '2861a270e3',
        "hall_code": 'HALSJL',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '24501014',
        "session": '2023-2024',
        "entity_id": '5010',
        "subject_id": '05011',
        "name_en": 'JANNATUL FERDOUS',
        "name_bn": 'জান্নাতুল ফেরদৌস',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2005-03-23',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": '1522927415',
        "phone": '01711055038',
        "both_address_same": 0,
        "perm_dist": 'Patuakhali',
        "fname_en": 'MD FARUK MOLLA',
        "fname_bn": 'মোঃ ফারুক মোল্লা',
        "mname_en": 'SONIA AKTER',
        "mname_bn": 'সোনিয়া আক্তার',
        "rand_hash": '9c8904ce22',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '19303058',
        "session": '2018-2019',
        "entity_id": '3030',
        "subject_id": '03031',
        "name_en": 'MISKAT MARUF',
        "name_bn": 'মিসকাত মারুফ',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2001-04-15',
        "nationality": 'Bangladeshi',
        "phone": '01752598534',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "perm_pcode": '4343',
        "fname_en": 'MD. BORHAN UDDIN CHOWDHURY',
        "fname_bn": 'বোরহান উদ্দীন চৌধুরী',
        "fphone": '01817713834',
        "mname_en": 'ROZINA AKTER',
        "mname_bn": 'রোজিনা আক্তার ',
        "rand_hash": '325383d5d0',
        "student_status": 1,
    },

    {
        "student_id": '20607009',
        "session": '2019-2020',
        "entity_id": '6070',
        "subject_id": '06071',
        "name_en": 'SHREYA DHAR',
        "name_bn": 'শ্রেয়া ধর',
        "gender": 'FEMALE',
        "dob_ymd": '2000-09-04',
        "nationality": 'Bangladeshi',
        "phone": '01852675825',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "perm_pcode": '4212',
        "fname_en": 'KANCHAN DHAR',
        "mname_en": 'PUTUL DHAR',
        "rand_hash": '54144dc5e7',
        "student_status": 1,
    },

    {
        "student_id": '24113049',
        "session": '2023-2024',
        "entity_id": '1130',
        "subject_id": '01131',
        "name_en": 'OMAR FARUK',
        "name_bn": 'ওমর ফারুক',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2004-10-06',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": '1042180693',
        "phone": '01813358733',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "fname_en": 'KAMAL HOSSAIN',
        "fname_bn": 'কামাল হোছাইন',
        "fphone": '01816152613',
        "mname_en": 'RAHIMA BEGUM',
        "mname_bn": 'রহিমা বেগম',
        "rand_hash": '6b8ba93930',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '23405017',
        "session": '2022-2023',
        "entity_id": '4050',
        "subject_id": '04051',
        "name_en": 'DURLOV ADHIKARY',
        "name_bn": 'দূর্লভ অধিকারী',
        "gender": 'MALE',
        "religion": 'HINDUISM',
        "dob_ymd": '2004-04-15',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": '7368717778',
        "phone": '01754177262',
        "both_address_same": 0,
        "fname_en": 'DIP ADHIKARY',
        "mname_en": 'POLY ADHIKARY',
        "rand_hash": 'bf6dd1fa0c',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '24605042',
        "session": '2023-2024',
        "entity_id": '6050',
        "subject_id": '06051',
        "name_en": 'MARIA SIDDIKA',
        "name_bn": 'মারিয়া ছিদ্দিকা',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2005-01-07',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": '2874678002',
        "phone": '01886104329',
        "both_address_same": 0,
        "perm_dist": "Cox's Bazar",
        "fname_en": 'SHAHIDUR RAHMAN',
        "fname_bn": 'শহিদুর রহমান',
        "fphone": '01850104329',
        "mname_en": 'RAHELA AKTER',
        "mname_bn": 'রাহেলা আক্তার',
        "rand_hash": 'dab60ae2f9',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '19113105',
        "session": '2018-2019',
        "entity_id": '1130',
        "subject_id": '01131',
        "name_en": 'HABIBA TAMANNA',
        "name_bn": 'হাবিবা তামান্না',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2001-10-20',
        "nationality": 'Bangladeshi',
        "phone": '01752110385',
        "both_address_same": 0,
        "perm_dist": 'Shariatpur',
        "perm_pcode": '8020',
        "fname_en": 'MD ABDUL HANNAN SIKDER',
        "fname_bn": 'মোঃ আব্দুল হান্নান শিকদার',
        "fphone": '01752110385',
        "mname_en": 'SULTANA HANNAN',
        "mname_bn": 'সুলতানা হান্নান',
        "rand_hash": '641ce23ad2',
        "student_status": 1,
    },

    {
        "student_id": '2604041020',
        "session": '2025-2026',
        "entity_id": '04040',
        "subject_id": '04041',
        "name_en": 'MST. ELMA KHATUN',
        "name_bn": 'মোছাঃ এলমা খাতুন',
        "gender": 'FEMALE',
        "religion": 'Islam',
        "dob": '21/07/2006',
        "dob_ymd": '2006-07-21',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": '20065019414060005',
        "phone": '01787285055',
        "both_address_same": 0,
        "perm_addr": 'Amla, Amla, Amla, Mirpur, Kushtia',
        "perm_dist": 'Kushtia',
        "perm_pcode": '7032',
        "pres_addr": 'Bismillah vaban-1, Jobra, Chitt, Hathazari, Chattogram',
        "pres_dist": 'Chattogram',
        "pres_pcode": '4331',
        "fname_en": 'MD. EMDADUL HAQUE',
        "fname_bn": 'মোঃ এমদাদুল হক',
        "fnid": '3265255111',
        "foccupation": 'Government employee',
        "fphone": '01712155550',
        "mname_en": 'MST. NASIMA KHATUN',
        "mname_bn": 'মোছাঃ নাছিমা খাতুন',
        "mnid": '2815259664',
        "mphone": '01715225230',
        "rand_hash": 'eff5796f82',
        "hall_code": 'HALSNR',
        "student_status": 1,
        "adm_unit": 'D',
        "adm_quota": 'GENERAL',
        "adm_roll": '644686',
        "hsc_group": 'hum',
        "adm_merit": '1060',
        "user_id": 140821,
        "username": 'jes24657270',
    },

    {
        "student_id": '20112007',
        "session": '2019-2020',
        "entity_id": '1120',
        "subject_id": '01121',
        "name_en": 'NUSRAT JAHAN HANNA',
        "name_bn": 'নুসরাত জাহান হান্না',
        "gender": 'FEMALE',
        "dob_ymd": '2001-10-02',
        "nationality": 'Bangladeshi',
        "phone": '01736431135',
        "both_address_same": 0,
        "perm_dist": 'Brahmanbaria',
        "perm_pcode": '3450',
        "fname_en": 'SANAUL HAQUE SANU',
        "mname_en": 'HALLIMA BEGUM',
        "rand_hash": 'fab81f5a9b',
        "student_status": 1,
    },

    {
        "student_id": '2503051056',
        "session": '2024-2025',
        "entity_id": '03050',
        "subject_id": '03051',
        "name_en": 'RUDMILA AZAM',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2006-12-12',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "phone": '01712507308',
        "both_address_same": 0,
        "fname_en": 'M. MOSHIUL AZAM',
        "fphone": '01712507308',
        "mname_en": 'MONIRA LAIZU',
        "mphone": '01717719322',
        "rand_hash": 'b03815741e',
        "hall_code": 'HALKHZ',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '23116027',
        "session": '2022-2023',
        "entity_id": '1160',
        "subject_id": '01161',
        "name_en": 'EMON NATH',
        "name_bn": 'ইমন নাথ',
        "gender": 'MALE',
        "religion": 'HINDUISM',
        "dob_ymd": '2001-02-10',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": '8708744308',
        "phone": '01779275591',
        "both_address_same": 0,
        "fname_en": 'SURANJIT NATH',
        "mname_en": 'ANIMA NATH',
        "rand_hash": 'c8ad062471',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '21208020',
        "session": '2020-2021',
        "entity_id": '2080',
        "subject_id": '02081',
        "name_en": 'MD. MEHEDI AMAN',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2002-11-28',
        "bloodgroup": 'AB+',
        "nationality": 'Bangladeshi',
        "phone": '01873827392',
        "both_address_same": 0,
        "perm_addr": "Muktarkul, Jhilongja, Cox's Bazar, Coxs_Bazar",
        "perm_dist": "Cox's Bazar",
        "fname_en": 'MD. NURUL AMIN',
        "fname_bn": 'মো: নুরুল আমিন',
        "fphone": '01814480582',
        "mname_en": 'SHAHIDA AKTER',
        "mname_bn": 'সাহিদা আক্তার',
        "rand_hash": '8f36482490',
        "student_status": 1,
        "adm_quota": 'General',
    },

    {
        "student_id": '2606021039',
        "session": '2025-2026',
        "entity_id": '06020',
        "subject_id": '06021',
        "name_en": 'TASNOVA JAHAN OTHY',
        "name_bn": 'তাসনূভা জাহান অথৈ',
        "gender": 'FEMALE',
        "religion": 'Islam',
        "dob": '09/02/2007',
        "dob_ymd": '2007-02-09',
        "bloodgroup": 'B-',
        "nationality": 'Bangladeshi',
        "nid": '20054819254104726',
        "phone": '01608439761',
        "both_address_same": 1,
        "perm_addr": 'Dewati, Jawar, Tarial, Tarial, Kishoreganj',
        "perm_dist": 'Kishoreganj',
        "perm_pcode": '2316',
        "pres_addr": 'Dewati, Jawar, Tarial, Tarial, Kishoreganj',
        "pres_dist": 'Kishoreganj',
        "pres_pcode": '2316',
        "fname_en": 'MD. LITON MIA',
        "fname_bn": 'মোঃ লিটন মিয়া',
        "fnid": '19724819254010403',
        "foccupation": 'Business',
        "fphone": '01742832852',
        "mname_en": 'MST. FAZILA ARFIN',
        "mname_bn": 'মোছাঃ ফজিলা আরফিন',
        "mnid": '4163893367',
        "mphone": '01752340442',
        "rand_hash": '47dd127c62',
        "hall_code": 'HALPRT',
        "student_status": 1,
        "adm_unit": 'A',
        "adm_quota": 'GENERAL',
        "adm_roll": '123878',
        "hsc_group": 'sci',
        "adm_merit": '2407',
        "user_id": 28457,
        "username": 'dha24195474',
    },

    {
        "student_id": '2604011078',
        "session": '2025-2026',
        "entity_id": '04010',
        "subject_id": '04011',
        "name_en": 'THANJINA AKTER THANHA',
        "name_bn": 'তানজিনা আক্তার তানহা',
        "gender": 'FEMALE',
        "religion": 'Islam',
        "dob": '14/10/2007',
        "dob_ymd": '2007-10-14',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "nid": '20071522203120372',
        "phone": '01622726066',
        "both_address_same": 1,
        "perm_addr": 'Chittagong, Fatickchari, South Rangamati, Sabir Mohammad Chowdhury Bari, South Rangamati, 03, Fatikchhari, Fatikchhari, Chattogram',
        "perm_dist": 'Chattogram',
        "perm_pcode": '4350',
        "pres_addr": 'Chittagong ,Fatickchari, South Rangamati, Sabir Mohammad Chowdhury Bari, South Rangamati, 03, Fatikchhari, Fatikchhari, Chattogram',
        "pres_dist": 'Chattogram',
        "pres_pcode": '4350',
        "fname_en": 'MD. ALAMGIR CHOWDHURY',
        "fname_bn": 'মোঃ আলমগীর চৌধুরী',
        "fnid": '19641522203119641',
        "foccupation": 'Deceased',
        "fphone": '01831414999',
        "mname_en": 'HASINA BEGUM',
        "mname_bn": 'হাছিনা বেগম',
        "mnid": '6881523580',
        "mphone": '01814873616',
        "rand_hash": 'f98e501334',
        "hall_code": 'HALSNR',
        "student_status": 1,
        "adm_unit": 'D',
        "adm_quota": 'GENERAL',
        "adm_roll": '614118',
        "hsc_group": 'bus',
        "adm_merit": '436',
        "user_id": 104889,
        "username": 'chi25507296',
    },

    {
        "student_id": '23203079',
        "session": '2022-2023',
        "entity_id": '2030',
        "subject_id": '02031',
        "name_en": 'TAHMINA AKTER',
        "name_bn": 'তাহমিনা আকতার',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2004-01-09',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": "20047526004123800",
        "phone": '01810996331',
        "both_address_same": 0,
        "fname_en": 'MD. NURULLAH TALOK',
        "mname_en": 'JOBAIDA BEGUM',
        "rand_hash": '5d26b0f5b3',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '2502011072',
        "session": '2024-2025',
        "entity_id": '02010',
        "subject_id": '02011',
        "name_en": 'APURBO CHANDRO RAY',
        "gender": 'MALE',
        "religion": 'HINDUISM',
        "dob_ymd": '2006-01-11',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "phone": '01581419786',
        "both_address_same": 0,
        "fname_en": 'DIPONGKOR RAY',
        "fphone": '01791399928',
        "mname_en": 'RANI SEN',
        "mphone": '01791399928',
        "rand_hash": 'f9ffa00a25',
        "hall_code": 'HALATS',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '23303093',
        "session": '2022-2023',
        "entity_id": '3030',
        "subject_id": '03031',
        "name_en": 'ABU SUFIYAN',
        "name_bn": 'আবু সুফিয়ান',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '0000-00-00',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "phone": '01776469957',
        "both_address_same": 0,
        "perm_dist": 'Cumilla',
        "fname_en": 'YASIN MOZUMDER',
        "fname_bn": 'মোঃ এয়াছিন মজুমদার',
        "fphone": '01714487744',
        "mname_en": 'MORSHEDA AKTER',
        "mname_bn": 'মোসাঃ মোর্শেদা আক্তার লিনা',
        "rand_hash": '9167782692',
        "student_status": 1,
        "adm_quota": 'FFQ2',
    },

    {
        "student_id": '21204090',
        "session": '2020-2021',
        "entity_id": '2040',
        "subject_id": '02041',
        "name_en": 'TANVIR AHMED MARUF',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2002-11-09',
        "bloodgroup": 'AB+',
        "nationality": 'Bangladeshi',
        "phone": '01788700026',
        "both_address_same": 0,
        "perm_addr": '777 Jaina Bari Road,  Jharka,  Ghatail,  Tangail, 1980, Ghatail, Tangail',
        "perm_dist": 'Tangail',
        "fname_en": 'MD. HARUN OR RASHID TALUKDER',
        "fname_bn": 'মোঃ হারুন অর রশীদ তালুকদার',
        "fphone": '01726121985',
        "mname_en": 'MST. MANOARA PARVIN',
        "mname_bn": 'মোছাঃ মনোয়ারা পারভীন',
        "rand_hash": 'bea93f28db',
        "student_status": 1,
        "adm_quota": 'General',
    },

    {
        "student_id": '22408001',
        "session": '2021-2022',
        "entity_id": '4080',
        "subject_id": '04081',
        "name_en": 'MD. SHAHEDUR RAHMAN SABBIR',
        "name_bn": 'মোঃ সাহেদুর রহমান সাব্বির',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2001-12-16',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": "20011513347108000",
        "phone": '01859827939',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "fname_en": 'MUSTAFIZUR RAHMAN',
        "fname_bn": 'মোস্তাফিজুর রহমান',
        "fphone": '01516358210',
        "mname_en": 'SHAHEDA AKTHER',
        "mname_bn": 'শাহেদা আকতার',
        "rand_hash": '908f540a39',
        "student_status": 1,
    },

    {
        "student_id": '20103129',
        "session": '2019-2020',
        "entity_id": '1030',
        "subject_id": '01031',
        "name_en": 'MOSAMMAT THAMINA SULTANA',
        "name_bn": 'মোছাম্মৎ তাহমিনা  সুলতানা',
        "gender": 'FEMALE',
        "dob_ymd": '2002-10-02',
        "nationality": 'Bangladeshi',
        "phone": '01838698709',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "perm_pcode": '4350',
        "fname_en": 'MD. AZHARUL ISLAM',
        "mname_en": 'MOSAMMAT RUBY AKHTER',
        "rand_hash": '7c35c2f32a',
        "student_status": 1,
    },

    {
        "student_id": '2501051001',
        "session": '2024-2025',
        "entity_id": '01050',
        "subject_id": '01051',
        "name_en": 'REHNUMA ISLAM',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2007-01-01',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "phone": '01614715331',
        "both_address_same": 0,
        "fname_en": 'MD. SAIFUL ISLAM',
        "fphone": '01714666614',
        "mname_en": 'JANNATUL FERDOUS',
        "mphone": '01734782909',
        "rand_hash": '321aa1afb8',
        "hall_code": 'HALKHZ',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '23403095',
        "session": '2022-2023',
        "entity_id": '4030',
        "subject_id": '04031',
        "name_en": 'SUFI TAHMIDUR RAHMAN',
        "name_bn": 'সুফী তাহমিদুর রহমান',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2004-03-17',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "nid": '9585969604',
        "phone": '01700763179',
        "both_address_same": 0,
        "fname_en": 'SUFI ABIDUR RAHMAN',
        "mname_en": 'SALINA YEASMIN',
        "rand_hash": '11e2dc4d99',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '23702014',
        "session": '2022-2023',
        "entity_id": '7020',
        "subject_id": '07021',
        "name_en": 'MD. SHAHRUKH IBNE ZAMAN',
        "name_bn": 'মো:শাহরুখ ইবনে জামান',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2004-12-27',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": '8724438927',
        "phone": '01678690208',
        "both_address_same": 0,
        "fname_en": 'SHOWKAT ZAMAN',
        "mname_en": 'KAMRUN NAHAR',
        "rand_hash": '86aabbe239',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '2606031049',
        "session": '2025-2026',
        "entity_id": '06030',
        "subject_id": '06031',
        "name_en": 'MD. MAHIBI ARPO MONAZ',
        "name_bn": 'মোঃ মাহিবী অর্প মোনাজ',
        "gender": 'MALE',
        "religion": 'Islam',
        "dob": '22/05/2007',
        "dob_ymd": '2007-05-22',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": '20077725003103560',
        "phone": '01628540923',
        "both_address_same": 0,
        "perm_addr": 'Islambug, Islambug, Ward-3, Panchagarh, Panchagarh Sadar, Panchagarh',
        "perm_dist": 'Panchagarh',
        "perm_pcode": 'Sadar',
        "pres_addr": 'Afsar Villa, 1 No. Rail Crossing, Fatehpur, Chittagong University Campus, Chitt, Hathazari, Chattogram',
        "pres_dist": 'Chattogram',
        "pres_pcode": '4331',
        "fname_en": 'MD. HASINUR RAHMAN',
        "fname_bn": 'মোঃ হাসিনুর রহমান',
        "fnid": '2815678970',
        "foccupation": 'Defense',
        "fphone": '01714335600',
        "mname_en": 'MST. MINNAT AMAN MUNNI',
        "mname_bn": 'মোছাঃ মিন্নাত আমান মুন্নী',
        "mnid": '4165679905',
        "mphone": '01722877766',
        "rand_hash": 'fd3765c5d4',
        "hall_code": 'HALSUH',
        "student_status": 1,
        "adm_unit": 'D',
        "adm_quota": 'GENERAL',
        "adm_roll": '629617',
        "hsc_group": 'hum',
        "adm_merit": '1612',
        "user_id": 75210,
        "username": 'dha25250956',
    },

    {
        "student_id": '20702035',
        "session": '2019-2020',
        "entity_id": '7020',
        "subject_id": '07021',
        "name_en": 'MD. SIYAM AHMED',
        "name_bn": 'মোঃ সিয়াম আহমেদ',
        "gender": 'MALE',
        "dob_ymd": '2001-12-27',
        "nationality": 'Bangladeshi',
        "phone": '01633193807',
        "both_address_same": 0,
        "perm_dist": 'Dhaka',
        "perm_pcode": '1361',
        "fname_en": 'MD. MOTIN MOLLAH',
        "mname_en": 'SOKINA BEGUM',
        "rand_hash": '8ad4ec4b06',
        "student_status": 1,
    },

    {
        "student_id": '19202115',
        "session": '2018-2019',
        "entity_id": '2020',
        "subject_id": '02021',
        "name_en": 'MD. MAMUN OR RASHID',
        "name_bn": 'মো: মামুন অর রশিদ ',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2001-10-01',
        "nationality": 'Bangladeshi',
        "phone": '01740329886',
        "both_address_same": 0,
        "perm_dist": 'Rangpur',
        "perm_pcode": '5470',
        "fname_en": 'MD. TOFAZZAL HOSSAIN',
        "fname_bn": 'মো: তোফাজ্জল হোসেন ',
        "fphone": '01740329886',
        "mname_en": 'MST. REKHA BEGUM',
        "mname_bn": 'মোছা: রেখা বেগম ',
        "rand_hash": '0ea86c7c90',
        "student_status": 1,
    },

    {
        "student_id": '2601081010',
        "session": '2025-2026',
        "entity_id": '01080',
        "subject_id": '01081',
        "name_en": 'BIQUEENSI CHAKMA',
        "name_bn": 'বিকুইনশি চাকমা',
        "gender": 'FEMALE',
        "religion": 'Buddho',
        "dob": '01/03/2006',
        "dob_ymd": '2006-03-01',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": '20068410711004975',
        "phone": '01553655972',
        "both_address_same": 0,
        "perm_addr": 'Ugalchari, Marishya, Baghai Chhari, Baghaichhari, Rangamati, Chattogram Division, Lambachara, Marishya, Marishya, Rangamati',
        "perm_dist": 'Rangamati',
        "perm_pcode": '4590',
        "pres_addr": 'Ugalchari,Marishya,Baghai Chhari,Baghaichhari,Rangamati, Chattogram Division, Lambachara, Marishya, Marishya, Rangamati',
        "pres_dist": 'Rangamati',
        "pres_pcode": '4590',
        "fname_en": 'DIPANKAR CHAKMA',
        "fname_bn": 'দীপংকর চাকমা',
        "fnid": '8410711278985',
        "foccupation": 'Farming',
        "fphone": '01821432825',
        "mname_en": 'SHEMPO CHAKMA',
        "mname_bn": 'সেম্পো চাকমা',
        "mnid": '8239025383',
        "mphone": '01531207665',
        "rand_hash": '92b609ce45',
        "hall_code": 'HALFAZ',
        "student_status": 1,
        "adm_unit": 'B2',
        "adm_quota": 'GENERAL',
        "adm_roll": '404056',
        "hsc_group": 'hum',
        "adm_merit": '846',
        "user_id": 43676,
        "username": 'chi24328263',
    },

    {
        "student_id": '21203136',
        "session": '2020-2021',
        "entity_id": '2030',
        "subject_id": '02031',
        "name_en": 'BURHAN UDDIN',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2000-05-20',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "phone": '01644821287',
        "both_address_same": 0,
        "perm_addr": "Bharua khali, Bharua Khali, Cox's Bazar Sodor, Coxs_Bazar",
        "perm_dist": "Cox's Bazar",
        "fname_en": 'EKHLAS KARIM',
        "fname_bn": 'একলাছ কবির',
        "fphone": '01752549832',
        "mname_en": 'TAFURA BEGUM',
        "mname_bn": 'তফুরা বেগম',
        "rand_hash": 'ad4303c7c5',
        "student_status": 1,
        "adm_quota": 'General',
    },

    {
        "student_id": '19208154',
        "session": '2018-2019',
        "entity_id": '2080',
        "subject_id": '02082',
        "name_en": 'TAKEYA TASNIM JHALAK',
        "name_bn": 'তাকিয়া তাসনিম ঝনক',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2000-06-06',
        "nationality": 'Bangladeshi',
        "phone": '01635263694',
        "both_address_same": 0,
        "perm_dist": "Cox's Bazar",
        "perm_pcode": '4700',
        "fname_en": 'BAZAL AHAMED SIKDER',
        "fname_bn": 'বজল আহমদ',
        "fphone": '01821835217',
        "mname_en": 'SHAFINA YEASMIN MARY',
        "mname_bn": 'সফিনা ইয়াসমিন মেরী',
        "rand_hash": '13005c2b09',
        "student_status": 1,
    },

    {
        "student_id": '2603061060',
        "session": '2025-2026',
        "entity_id": '03060',
        "subject_id": '03061',
        "name_en": 'JUBAIDA KHANAM MONA',
        "name_bn": 'জোবায়দা খানম মোনা',
        "gender": 'FEMALE',
        "religion": 'Islam',
        "dob": '06/06/2007',
        "dob_ymd": '2007-06-06',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": '5129352166',
        "phone": '01830186000',
        "both_address_same": 0,
        "perm_addr": 'Baktear Mazir Bari, Guman Mardan, Ward No-05, Hathazari, Hathazari, Chattogram',
        "perm_dist": 'Chattogram',
        "perm_pcode": '4330',
        "pres_addr": 'Eden City, Fatehabad, Fatahabad, Hathazari, Chattogram',
        "pres_dist": 'Chattogram',
        "pres_pcode": '4335',
        "fname_en": 'MD. JAHANGIR ALAM',
        "fname_bn": 'মোঃ জাহাঙ্গীর আলম',
        "fnid": '6903435409',
        "foccupation": 'Unemployed',
        "fphone": '01883208113',
        "mname_en": 'NASIMA AKTER',
        "mname_bn": 'নাছিমা আক্তার',
        "mnid": '8244983519',
        "mphone": '01830186000',
        "rand_hash": 'd2cc2549b4',
        "hall_code": 'HALPRT',
        "student_status": 1,
        "adm_unit": 'C',
        "adm_quota": 'GENERAL',
        "adm_roll": '507115',
        "hsc_group": 'bus',
        "adm_merit": '412',
        "user_id": 104285,
        "username": 'chi25502793',
    },

    {
        "student_id": '23403008',
        "session": '2022-2023',
        "entity_id": '4030',
        "subject_id": '04031',
        "name_en": 'TASPIYA BILKIS',
        "name_bn": 'তাসপিয়া বিলকিস',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2004-02-22',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": "200422166850156992",
        "phone": '01886814820',
        "both_address_same": 0,
        "fname_en": 'NURUL KABIR',
        "mname_en": 'NUR JAHAN BEGUM',
        "rand_hash": 'd0a6c8b50d',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '2502041054',
        "session": '2024-2025',
        "entity_id": '02040',
        "subject_id": '02041',
        "name_en": 'SHOAEB RAHMAN',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2007-08-15',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "phone": '01776334376',
        "both_address_same": 0,
        "fname_en": 'SHAHAJAHAN MAZUMDER',
        "fphone": '01857455329',
        "mname_en": 'SHAMEMA AKTHER',
        "mphone": '01912563899',
        "rand_hash": '5a8996fb5a',
        "hall_code": 'HALSJL',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '22701064',
        "session": '2021-2022',
        "entity_id": '7010',
        "subject_id": '07011',
        "name_en": 'UMMAY SABIRA',
        "name_bn": 'উম্মে সাবিরা',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2003-05-16',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "nid": "20031591603121000",
        "phone": '01618002863',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "fname_en": 'MAHABUB ALAM',
        "fname_bn": 'মাহাবুব আলম',
        "fphone": '01618002863',
        "mname_en": 'ASMA KHATUN',
        "mname_bn": 'আসমা খাতুন',
        "rand_hash": '457fd20262',
        "student_status": 1,
    },

    {
        "student_id": '2501111032',
        "session": '2024-2025',
        "entity_id": '01110',
        "subject_id": '01111',
        "name_en": 'BIBI AYSHA',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2005-07-02',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "phone": '01833249722',
        "both_address_same": 0,
        "fname_en": 'ALI AHMED',
        "fphone": '01825013965',
        "mname_en": 'RUBI AKTER',
        "mphone": '01833249722',
        "rand_hash": '41dff1b52d',
        "hall_code": 'HALPRT',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '22301051',
        "session": '2021-2022',
        "entity_id": '3010',
        "subject_id": '03011',
        "name_en": 'ERFAT REZA SIDDIQUE',
        "name_bn": 'ইরফাত রেজা সিদ্দিক',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2004-03-21',
        "bloodgroup": 'AB+',
        "nationality": 'Bangladeshi',
        "nid": "20041591630115200",
        "phone": '01317674976',
        "both_address_same": 0,
        "perm_dist": 'Mymensingh',
        "fname_en": 'REZAUL KARIM SIDDIQUE',
        "fname_bn": 'রেজাউল করিম সিদ্দিক',
        "fphone": '01670388163',
        "rand_hash": 'c205f5be7a',
        "student_status": 1,
    },

    {
        "student_id": '2601081070',
        "session": '2025-2026',
        "entity_id": '01080',
        "subject_id": '01081',
        "name_en": 'SHREYA CHAKMA',
        "name_bn": 'শ্রেয়া চাকমা',
        "gender": 'FEMALE',
        "religion": 'Buddho',
        "dob": '13/02/2006',
        "dob_ymd": '2006-02-13',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": '4668790118',
        "phone": '01518322311',
        "both_address_same": 0,
        "perm_addr": 'Babuchara, Ward-01, Diginala, Diginala, Khagrachari',
        "perm_dist": 'Khagrachari',
        "perm_pcode": '4420',
        "pres_addr": 'Bondhon House, Chittagong University 2 no gate, Chitt, Hathazari, Chattogram',
        "pres_dist": 'Chattogram',
        "pres_pcode": '4331',
        "fname_en": 'BODHI SATTA CHAKMA',
        "fname_bn": 'বোধিসত্ত্ব চাকমা',
        "fnid": '9127840388',
        "foccupation": 'Farming',
        "fphone": '01820747404',
        "mname_en": 'MADHURIKA CHAKMA',
        "mname_bn": 'মাধুরিকা চাকমা',
        "mnid": '5077825551',
        "mphone": '01585464057',
        "rand_hash": '111ebfaa27',
        "hall_code": 'HALFAZ',
        "student_status": 1,
        "adm_unit": 'B2',
        "adm_quota": 'GENERAL',
        "adm_roll": '400845',
        "hsc_group": 'hum',
        "adm_merit": '812',
        "user_id": 27156,
        "username": 'chi24335400',
    },

    {
        "student_id": '2506041025',
        "session": '2024-2025',
        "entity_id": '06040',
        "subject_id": '06041',
        "name_en": 'FARJANA ALAM FABI',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2007-01-22',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "phone": '01987780575',
        "both_address_same": 0,
        "fname_en": 'MAHBOBUL ALAM',
        "fphone": '01714449391',
        "mname_en": 'SALMA AKTER',
        "mphone": '01621782353',
        "rand_hash": 'f2822310c0',
        "hall_code": 'HALPRT',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '24408032',
        "session": '2023-2024',
        "entity_id": '4080',
        "subject_id": '04081',
        "name_en": 'MD. MUSAHAN ISLAM',
        "name_bn": 'মো: মুসাহান ইসলাম',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2005-03-03',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": '7375869968',
        "phone": '01328706550',
        "both_address_same": 0,
        "perm_dist": 'Thakurgaon',
        "fname_en": 'MD. MORTUZA',
        "fname_bn": 'মো: মর্তুজা',
        "fphone": '01568452437',
        "mname_en": 'MST. BAKUL BANU',
        "mname_bn": 'মোছা: বকুল বানু',
        "rand_hash": '50e7138919',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '2606011047',
        "session": '2025-2026',
        "entity_id": '06010',
        "subject_id": '06011',
        "name_en": 'AKASH SAHA',
        "name_bn": 'আকাশ সাহা',
        "gender": 'MALE',
        "religion": 'Hindu',
        "dob": '22/11/2006',
        "dob_ymd": '2006-11-22',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": '1035036241',
        "phone": '01877940635',
        "both_address_same": 1,
        "perm_addr": 'South Chnua, 10 number union, Feni Sadar Feni, South Chnua, Fazilpur, Feni Sadar, Feni',
        "perm_dist": 'Feni',
        "perm_pcode": '3901',
        "pres_addr": 'South Chnua,10 number union, Feni Sadar Feni, South Chnua, Fazilpur, Feni Sadar, Feni',
        "pres_dist": 'Feni',
        "pres_pcode": '3901',
        "fname_en": 'DELIP KUMAR SAHA',
        "fname_bn": 'দিলীপ কুমার সাহা',
        "fnid": '4614312041',
        "foccupation": 'Farming',
        "fphone": '01832945353',
        "mname_en": 'LAKKHI RANI SAHA',
        "mname_bn": 'লক্ষী রানী সাহা',
        "mnid": '2364297537',
        "mphone": '01832945353',
        "rand_hash": 'f51918aa4e',
        "hall_code": 'HALATS',
        "student_status": 1,
        "adm_unit": 'A',
        "adm_quota": 'GENERAL',
        "adm_roll": '125811',
        "hsc_group": 'sci',
        "adm_merit": '3141',
        "user_id": 54174,
        "username": 'com25173448',
    },

    {
        "student_id": '2504021016',
        "session": '2024-2025',
        "entity_id": '04020',
        "subject_id": '04021',
        "name_en": 'KHADIZA AKTAR',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2004-08-01',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "phone": '01615936323',
        "both_address_same": 0,
        "fname_en": 'MD.JAMAL UDDIN',
        "fphone": '01720243527',
        "mname_en": 'NURSAHIDA',
        "mphone": '01726878521',
        "rand_hash": '1c0fb2e47f',
        "hall_code": 'HALBIJ',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '20407018',
        "session": '2019-2020',
        "entity_id": '4070',
        "subject_id": '04071',
        "name_en": 'MD. YEASIN',
        "name_bn": 'মোঃ ইয়াছিন',
        "gender": 'MALE',
        "dob_ymd": '2001-02-10',
        "nationality": 'Bangladeshi',
        "phone": '01869202576',
        "both_address_same": 0,
        "perm_dist": 'Chandpur',
        "perm_pcode": '3632',
        "fname_en": 'MD. ABDUL HAI',
        "mname_en": 'RAHIMA BEGUM',
        "rand_hash": 'c3de32ea8a',
        "student_status": 1,
    },

    {
        "student_id": '2604011015',
        "session": '2025-2026',
        "entity_id": '04010',
        "subject_id": '04011',
        "name_en": 'MST.SAWDA AKTER JARIN',
        "name_bn": 'সাওদা আক্তার জেরিন',
        "gender": 'FEMALE',
        "religion": 'Islam',
        "dob": '04/10/2007',
        "dob_ymd": '2007-10-04',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "nid": '20074817627105025',
        "phone": '01972484562',
        "both_address_same": 0,
        "perm_addr": 'Dampara, nikli, Kishoreganj, Dampara, Nikli, Nikli, Kishoreganj',
        "perm_dist": 'Kishoreganj',
        "perm_pcode": '2360',
        "pres_addr": 'South campus, University of Chittagong, Fatehpur, Chitt, Hathazari, Chattogram',
        "pres_dist": 'Chattogram',
        "pres_pcode": '4331',
        "fname_en": 'MD.RAFIQUL ISLAM',
        "fname_bn": 'রফিকুল ইসলাম',
        "fnid": '4817627211225',
        "foccupation": 'Farming',
        "fphone": '01712440638',
        "mname_en": 'MST.SHAHINA AKTER BEAUTY',
        "mname_bn": 'শাহিনা আক্তার বিউটি',
        "mnid": '4817627211114',
        "mphone": '01759343159',
        "rand_hash": '966fba3a47',
        "hall_code": 'HALBIJ',
        "student_status": 1,
        "adm_unit": 'D',
        "adm_quota": 'GENERAL',
        "adm_roll": '639136',
        "hsc_group": 'hum',
        "adm_merit": '368',
        "user_id": 134940,
        "username": 'dha25379589',
    },

    {
        "student_id": '23605040',
        "session": '2022-2023',
        "entity_id": '6050',
        "subject_id": '06051',
        "name_en": 'SALMA KHANAM NURI',
        "name_bn": 'সালমা খানম নুরী',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2003-09-12',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": '8258617052',
        "phone": '01537225645',
        "both_address_same": 0,
        "fname_en": 'SAYED NOOR',
        "mname_en": 'JUBADANNAHAR MINU',
        "rand_hash": 'b1d305c9da',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '24204115',
        "session": '2023-2024',
        "entity_id": '2040',
        "subject_id": '02041',
        "name_en": 'MD. SHAMIM HSSAIN',
        "name_bn": 'মোঃ শামীম হোসেন',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2003-06-19',
        "bloodgroup": 'A+',
        "nationality": 'Bangladeshi',
        "nid": '1036476875',
        "phone": '01568379951',
        "both_address_same": 0,
        "perm_dist": 'Jhenaidah',
        "fname_en": 'MD. KALAM HOSSAIN',
        "fname_bn": 'মোঃ কালাম হোসেন',
        "fphone": '01586000740',
        "mname_en": 'MST. PARVINA KHATUN',
        "mname_bn": 'মোছাঃ পারভীনা খাতুন',
        "rand_hash": 'a5cc97c195',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '20404098',
        "session": '2019-2020',
        "entity_id": '4040',
        "subject_id": '04041',
        "name_en": 'SADIA NAJNIN RIMU',
        "name_bn": 'সাদিয়া নাজনীন রীমু',
        "gender": 'FEMALE',
        "dob_ymd": '2003-01-01',
        "nationality": 'Bangladeshi',
        "phone": '01735462258',
        "both_address_same": 0,
        "perm_dist": 'Narsingdi',
        "perm_pcode": '1650',
        "fname_en": 'SAIFUL ISLAM JAMIR',
        "mname_en": 'NURJAHAN',
        "rand_hash": 'c65020be5a',
        "student_status": 1,
    },

    {
        "student_id": '20107026',
        "session": '2019-2020',
        "entity_id": '1070',
        "subject_id": '01071',
        "name_en": 'JABED HOSEN',
        "name_bn": 'জাবেদ হোসেন',
        "gender": 'MALE',
        "dob_ymd": '2001-10-15',
        "nationality": 'Bangladeshi',
        "phone": '01885241951',
        "both_address_same": 0,
        "perm_dist": 'Chandpur',
        "fname_en": 'CHAN MIAH MIJI',
        "mname_en": 'SAHEDA BEGUM',
        "rand_hash": '37d0dcd735',
        "student_status": 1,
    },

    {
        "student_id": '23104036',
        "session": '2022-2023',
        "entity_id": '1040',
        "subject_id": '01041',
        "name_en": 'JUE SHARKER',
        "name_bn": 'জুঁই সরকার',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2004-11-02',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": "20048814476000600",
        "phone": '01746152583',
        "both_address_same": 0,
        "fname_en": 'MD. RAFIQUL ISLAM',
        "mname_en": 'AMENA KHATUN BINA',
        "rand_hash": '22618811d7',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '2601011027',
        "session": '2025-2026',
        "entity_id": '01010',
        "subject_id": '01011',
        "name_en": 'SANJIDA SULTANA RITA',
        "name_bn": 'সানজিদা সুলতানা রিতা',
        "gender": 'FEMALE',
        "religion": 'Islam',
        "dob": '14/11/2006',
        "dob_ymd": '2006-11-14',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": '20061518251116800',
        "phone": '01885623937',
        "both_address_same": 1,
        "perm_addr": 'NUR AHMED ER BARI, VILL- KANCHANA, Satkania, Satkania, Chattogram',
        "perm_dist": 'Chattogram',
        "perm_pcode": '4386',
        "pres_addr": 'NUR AHMED ER BARI, VILL- KANCHANA, Satkania, Satkania, Chattogram',
        "pres_dist": 'Chattogram',
        "pres_pcode": '4386',
        "fname_en": 'ALI AHMED',
        "fname_bn": 'আলী আহম্মদ',
        "fnid": '3286216522',
        "foccupation": 'BUSINESS',
        "fphone": '01817273437',
        "mname_en": 'FATEMA BEGUM',
        "mname_bn": 'ফাতেমা বেগম',
        "mnid": '1935853620',
        "mphone": '01837920989',
        "rand_hash": '6e14637227',
        "hall_code": 'HALPRT',
        "student_status": 1,
        "adm_unit": 'B',
        "adm_quota": 'GENERAL',
        "adm_roll": '216729',
        "hsc_group": 'hum',
        "adm_merit": '700',
        "user_id": 29057,
        "username": 'chi25311067',
    },

    {
        "student_id": '19501027',
        "session": '2018-2019',
        "entity_id": '5010',
        "subject_id": '05011',
        "name_en": 'VHUBAN CHANDRA DEY',
        "name_bn": 'ভুবন চন্দ্র দে',
        "gender": 'MALE',
        "religion": 'HINDUISM',
        "dob_ymd": '1999-10-10',
        "nationality": 'Bangladeshi',
        "phone": '01840252085',
        "both_address_same": 0,
        "perm_dist": "Cox's Bazar",
        "perm_pcode": '4710',
        "fname_en": 'SONTOSH KUMAR DEY',
        "fname_bn": 'সন্তোষ কুমার দে',
        "fphone": '01840252085',
        "mname_en": 'PROVA RANI DEY',
        "mname_bn": 'প্রভা রানী দে',
        "rand_hash": '49249ac11a',
        "student_status": 1,
    },

    {
        "student_id": '24107010',
        "session": '2023-2024',
        "entity_id": '1070',
        "subject_id": '01071',
        "name_en": 'AHMAD SALEH AN NAZIF',
        "name_bn": 'আহমাদ সালেহ আন নাযীফ',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2004-01-24',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "nid": '3324625080',
        "phone": '01870741937',
        "both_address_same": 0,
        "perm_dist": 'Jamalpur',
        "fname_en": 'MD. BAZLUR RAHMAN',
        "fname_bn": 'মোঃ বজলুর রহমান',
        "fphone": '01922183501',
        "mname_en": 'NAZMA AKTER',
        "mname_bn": 'নাজমা আক্তার',
        "rand_hash": '4f8c1c85a7',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '22110022',
        "session": '2021-2022',
        "entity_id": '1100',
        "subject_id": '01101',
        "name_en": 'MD. ISMAIL SARDAR',
        "name_bn": 'মোঃ ইসমাইল সর্দার',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2000-01-01',
        "bloodgroup": 'O-',
        "nationality": 'Bangladeshi',
        "nid": '6903041017',
        "phone": '01876457928',
        "both_address_same": 0,
        "perm_dist": 'Chandpur',
        "fname_en": 'MD. HOSEN SARDAR',
        "fname_bn": 'মোঃ হোসেন সর্দার',
        "fphone": '01876457928',
        "mname_en": 'AMENA BEGUM',
        "mname_bn": 'আমেনা বেগম',
        "rand_hash": '0795198f06',
        "student_status": 1,
    },

    {
        "student_id": '20903010',
        "session": '2019-2020',
        "entity_id": '9030',
        "subject_id": '09031',
        "name_en": 'SUJOY KOR LIMON',
        "name_bn": 'সুজয় কর লিমন',
        "gender": 'MALE',
        "dob_ymd": '2000-01-02',
        "nationality": 'Bangladeshi',
        "phone": '01871152802',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "perm_pcode": '4360',
        "fname_en": 'ANIL KUMAR SHILL',
        "mname_en": 'NILIMA SHILL',
        "rand_hash": 'a95f25ef6e',
        "student_status": 1,
    },

    {
        "student_id": '2505011101',
        "session": '2024-2025',
        "entity_id": '05010',
        "subject_id": '05011',
        "name_en": 'MD. SAYEED HOSSAIN',
        "gender": 'MALE',
        "religion": 'ISLAM',
        "dob_ymd": '2007-05-28',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "phone": '01866686334',
        "both_address_same": 0,
        "fname_en": 'MD. TOFAZZAL HOSSAIN',
        "fphone": '01851757088',
        "mname_en": 'SALEHA  BEGUM',
        "mphone": '01720641368',
        "rand_hash": 'da55105da0',
        "hall_code": 'HALSMT',
        "student_status": 1,
        "adm_quota": 'GENERAL',
    },

    {
        "student_id": '21114035',
        "session": '2020-2021',
        "entity_id": '1140',
        "subject_id": '01141',
        "name_en": 'RAHANUMA TARANNUM',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2001-11-07',
        "bloodgroup": 'O+',
        "nationality": 'Bangladeshi',
        "phone": '01867112550',
        "both_address_same": 0,
        "perm_addr": 'Village: Jafar Nagar, , Jafar Nagar, Sitakunda, Chittagong',
        "perm_dist": 'Chattogram',
        "fname_en": 'NASIR UDDIN CHOWDHURY',
        "fname_bn": 'নাছির উদ্দীন চৌধুরী',
        "fphone": '01919210292',
        "mname_en": 'RAHIMA KHATUN',
        "mname_bn": 'রহিমা খাতুন',
        "rand_hash": 'd0f9d7921e',
        "student_status": 1,
        "adm_quota": 'General',
    },

    {
        "student_id": '22201036',
        "session": '2021-2022',
        "entity_id": '2010',
        "subject_id": '02011',
        "name_en": 'TAMANNA TABASSUM MUMU',
        "name_bn": 'তামান্না তাবাসসুম মুমু',
        "gender": 'FEMALE',
        "religion": 'ISLAM',
        "dob_ymd": '2003-09-02',
        "bloodgroup": 'B+',
        "nationality": 'Bangladeshi',
        "nid": '1972783128',
        "phone": '01997196040',
        "both_address_same": 0,
        "perm_dist": 'Chattogram',
        "fname_en": 'MD. MORSHEDUL ALAM',
        "fname_bn": 'মোহাম্মদ মোরশেদুল আলম',
        "fphone": '01997196040',
        "mname_en": 'SHARABON TAHURA LUCKY',
        "mname_bn": 'সারাবন তাহুরা',
        "rand_hash": 'efadc77b0d',
        "student_status": 1,
    },

]


class Command(BaseCommand):
    help = "Seed student records"

    @transaction.atomic
    def handle(self, *args, **options):
        created = 0
        updated = 0

        for data in STUDENTS:
            student_id = data["student_id"]
            defaults = {k: v for k, v in data.items() if k != "student_id"}

            _, is_created = Student.objects.update_or_create(
                student_id=student_id,
                defaults=defaults,
            )

            if is_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Students seeded successfully. "
                f"Created: {created}, Updated: {updated}"
            )
        )
