# Generated by Django 6.1 on 2026-08-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='hall_type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', help_text='Male or female hall.', max_length=1),
        ),
        migrations.AddField(
            model_name='hall',
            name='minority',
            field=models.CharField(choices=[('Y', 'Yes (Minority / Ethnic)'), ('N', 'No')], default='N', help_text='Minority / ethnic hall flag.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hall',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='hall',
            constraint=models.UniqueConstraint(fields=('code', 'hall_type'), name='unique_hall_code_per_type'),
        ),
    ]
