# Generated by Django 6.1 on 2026-08-17 03:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=50)),
                ('order', models.PositiveSmallIntegerField(choices=[(1, 'Primary'), (2, 'Secondary')], default=1)),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('released', 'Released')], db_index=True, max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_logs', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_logs', to='halls.seat')),
            ],
            options={
                'verbose_name': 'Seat Assignment Log',
                'verbose_name_plural': 'Seat Assignment Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='Reason for blocking the seat.', max_length=255)),
                ('note', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='halls.seat')),
            ],
            options={
                'verbose_name': 'Seat Maintenance',
                'verbose_name_plural': 'Seat Maintenance Records',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, help_text='Student ID / Roll from the (separate) student table.', max_length=50)),
                ('order', models.PositiveSmallIntegerField(choices=[(1, 'Primary'), (2, 'Secondary')], default=1, help_text='Primary or Secondary student for a shared seat.')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='halls.seat')),
            ],
            options={
                'verbose_name': 'Seat Assignment',
                'verbose_name_plural': 'Seat Assignments',
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('seat', 'student_id'), name='unique_active_assignment_per_student'), models.CheckConstraint(condition=models.Q(('order__in', [1, 2])), name='assignment_order_in_primary_secondary')],
            },
        ),
    ]
