# Generated by Django 6.1 on 2026-09-02 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
        ('halls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seatmaintenance',
            name='ended_by',
            field=models.ForeignKey(blank=True, help_text='Manager who removed the seat from hold.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_ended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seatmaintenance',
            name='started_by',
            field=models.ForeignKey(blank=True, help_text='Manager who put the seat on hold.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_started', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SeatMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('put_on', 'Put on Maintenance'), ('removed', 'Removed from Maintenance')], db_index=True, max_length=10)),
                ('reason', models.CharField(blank=True, help_text='Reason copied from the maintenance record.', max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance', models.ForeignKey(blank=True, help_text='Source maintenance record, if still present.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='allocations.seatmaintenance')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_logs', to='halls.seat')),
            ],
            options={
                'verbose_name': 'Seat Maintenance Log',
                'verbose_name_plural': 'Seat Maintenance Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
