# Generated by Django 6.1 on 2026-08-19 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatReleaseReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Reason shown in the release dropdown.', max_length=255, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Seat Release Reason',
                'verbose_name_plural': 'Seat Release Reasons',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='released_reason',
            field=models.ForeignKey(blank=True, help_text='Reason selected when the seat was released from this student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='allocations.seatreleasereason'),
        ),
        migrations.AddField(
            model_name='seatassignmentlog',
            name='release_reason',
            field=models.ForeignKey(blank=True, help_text='Reason selected when a seat was released.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='allocations.seatreleasereason'),
        ),
    ]
