# Generated by Django 6.1 on 2026-09-02 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0002_maintenance_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatMaintenanceReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Reason shown in the maintenance dropdown.', max_length=255, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Manager who created this reason (null for system/default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_reasons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seat Maintenance Reason',
                'verbose_name_plural': 'Seat Maintenance Reasons',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='seatmaintenance',
            name='maintenance_reason',
            field=models.ForeignKey(blank=True, help_text='Selected maintenance reason (new).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='allocations.seatmaintenancereason'),
        ),
    ]
