# Generated by Django 6.1 on 2026-08-23 06:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0003_seed_release_reasons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, help_text='6-digit id: YYYY + 2-digit call number, e.g. 202601.', max_length=6, unique=True)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('sequence', models.PositiveSmallIntegerField(help_text='Call number within the year (from last two digits).')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Only one call can be active at a time.')),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Allocation Call',
                'verbose_name_plural': 'Allocation Calls',
                'ordering': ['-year', '-sequence'],
            },
        ),
        migrations.CreateModel(
            name='HallAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_code', models.CharField(db_index=True, help_text='Code of the hall allotted to the student.', max_length=6)),
                ('student_id', models.CharField(db_index=True, help_text='Student who received this allotment.', max_length=10)),
                ('merit_pos', models.IntegerField(help_text='Merit position used during the allocation.')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='allocations.allocationcall')),
            ],
            options={
                'verbose_name': 'Hall Allocation',
                'verbose_name_plural': 'Hall Allocations',
                'ordering': ['call__call_id', 'merit_pos'],
            },
        ),
        migrations.AddConstraint(
            model_name='allocationcall',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_allocation_call'),
        ),
        migrations.AddConstraint(
            model_name='hallallocation',
            constraint=models.UniqueConstraint(fields=('call', 'student_id'), name='unique_student_per_allocation_call'),
        ),
    ]
