# Generated by Django 6.1 on 2026-09-02 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0003_maintenance_reasons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seatreleasereason',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='seatreleasereason',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Manager who created this reason (null for system/default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_reasons', to=settings.AUTH_USER_MODEL),
        ),
    ]
