# Generated by Django 6.1 on 2026-08-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0004_allocationcall_hallallocation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hallallocation',
            name='unique_student_per_allocation_call',
        ),
        migrations.AlterField(
            model_name='hallallocation',
            name='student_id',
            field=models.CharField(db_index=True, help_text='Student who received this allotment. Unique across every allocation call.', max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='hallallocation',
            constraint=models.UniqueConstraint(fields=('student_id',), name='unique_student_across_calls'),
        ),
    ]
