# Generated by Django 6.1 on 2026-09-03 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0004_release_reason_owner'),
        ('halls', '0002_manager_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('assign', 'Mistaken Assign'), ('release', 'Mistaken Release')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('student_id', models.CharField(db_index=True, max_length=50)),
                ('reason', models.TextField(help_text='Why this assignment/release was mistaken.')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolve_requests', to='allocations.seatassignment')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolve_requests', to='halls.hall')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolve_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_requests', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolve_requests', to='halls.seat')),
            ],
            options={
                'verbose_name': 'Resolve Request',
                'verbose_name_plural': 'Resolve Requests',
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('assignment',), name='unique_pending_per_assignment')],
            },
        ),
    ]
