# Generated by Django 6.1 on 2026-08-30 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0005_remove_hallallocation_unique_student_per_allocation_call_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hallallocation',
            options={'ordering': ['call__call_id', 'student_id'], 'verbose_name': 'Hall Allocation', 'verbose_name_plural': 'Hall Allocations'},
        ),
        migrations.RemoveField(
            model_name='hallallocation',
            name='merit_pos',
        ),
    ]
