# Generated by Django 6.1 on 2026-08-30 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='event_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Assign / Release date-time printed on the slip'),
        ),
    ]
