# Generated by Django 6.1 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slips', '0002_slip_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='student_name_bn',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='slip',
            name='father_name_bn',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
